"""initial_schema

Revision ID: 438bb7068d5b
Revises: 
Create Date: 2026-05-18 05:35:35.440695

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '438bb7068d5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
