"""initial

Revision ID: c4072c8d7b25
Revises: 438bb7068d5b
Create Date: 2026-05-18 06:12:58.008234

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c4072c8d7b25'
down_revision: Union[str, None] = '438bb7068d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
